services:
  postgres:
    image: docker.io/library/postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: collct
      POSTGRES_PASSWORD: collct
      POSTGRES_DB: collct
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
